# Generated by Django 4.0.4 on 2022-08-20 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_users_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='RegisteredUsers',
        ),
    ]
