# Generated by Django 4.0.4 on 2022-08-20 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_rename_registeredusers_registereduser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registereduser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='registereduser',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='registereduser',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='registereduser',
            name='othername',
        ),
        migrations.RemoveField(
            model_name='registereduser',
            name='password',
        ),
        migrations.RemoveField(
            model_name='registereduser',
            name='username',
        ),
    ]
