# Generated by Django 4.0.4 on 2022-08-21 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommerce', '0006_registereduser_registerd_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registereduser',
            name='registerd_user',
            field=models.ForeignKey(default=int, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
