# Generated by Django 4.0.4 on 2022-08-21 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_rename_registerd_user_registereduser_register_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registereduser',
            name='register_user',
        ),
    ]
